package solutions.s4y.waytoday.sdk.id;

import androidx.annotation.NonNull;

/**
 * An interface used for the notification new TrackID generated by WayToday server
 */
public interface ITrackIDChangeListener {
    void onTrackID(@NonNull String trackID);
}
